#ifndef USER_CONFIG_H
#define USER_CONFIG_H

/*
 * 车辆状态估测方法：
 * USER_STATE_ESTIMATOR_RAW：基础直通估测，当前默认可用方法。
 * USER_STATE_ESTIMATOR_WEIGHTED：加权融合估测，当前预留入口。
 * USER_STATE_ESTIMATOR_COMPLEMENTARY：互补滤波估测，当前预留入口。
 * USER_STATE_ESTIMATOR_KALMAN：Kalman 估测，当前预留入口。
 * USER_STATE_ESTIMATOR_EKF：扩展 Kalman 估测，当前预留入口。
 *
 * 切换方式：
 * 1. 默认使用基础直通估测：保持默认配置。
 * 2. 需要测试预留入口时：改为对应的 USER_STATE_ESTIMATOR_xxx。
 *
 * 注意：预留入口在算法库接入前会自动回落到基础直通估测，不改变发布接口。
 */
#define USER_STATE_ESTIMATOR_RAW 0
#define USER_STATE_ESTIMATOR_WEIGHTED 1
#define USER_STATE_ESTIMATOR_COMPLEMENTARY 2
#define USER_STATE_ESTIMATOR_KALMAN 3
#define USER_STATE_ESTIMATOR_EKF 4

#ifndef USER_STATE_DEFAULT_ESTIMATOR
#define USER_STATE_DEFAULT_ESTIMATOR USER_STATE_ESTIMATOR_RAW
#endif

#if (USER_STATE_DEFAULT_ESTIMATOR != USER_STATE_ESTIMATOR_RAW) &&           \
    (USER_STATE_DEFAULT_ESTIMATOR != USER_STATE_ESTIMATOR_WEIGHTED) &&      \
    (USER_STATE_DEFAULT_ESTIMATOR != USER_STATE_ESTIMATOR_COMPLEMENTARY) && \
    (USER_STATE_DEFAULT_ESTIMATOR != USER_STATE_ESTIMATOR_KALMAN) &&        \
    (USER_STATE_DEFAULT_ESTIMATOR != USER_STATE_ESTIMATOR_EKF)
#error "USER_STATE_DEFAULT_ESTIMATOR must be a supported estimator method"
#endif

#endif /* USER_CONFIG_H */
